# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20171102_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
            preserve_default=False,
        ),
    ]
